// <auto-generated />
using System;
using BTCPayServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220601074750_AddSettingsToStore")]
    public partial class AddSettingsToStore : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Name",
                table: "Settings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "StoreId",
                table: "Settings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Settings_Name_StoreId",
                table: "Settings",
                columns: new[] {"Name", "StoreId"});

            migrationBuilder.CreateIndex(
                name: "IX_Settings_StoreId",
                table: "Settings",
                column: "StoreId");
            if (this.SupportAddForeignKey(ActiveProvider))
            {
                migrationBuilder.AddForeignKey(
                    name: "FK_Settings_Stores_StoreId",
                    table: "Settings",
                    column: "StoreId",
                    principalTable: "Stores",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade);
            }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Settings_Stores_StoreId",
                table: "Settings");

            migrationBuilder.DropIndex(
                name: "IX_Settings_Name_StoreId",
                table: "Settings");

            migrationBuilder.DropIndex(
                name: "IX_Settings_StoreId",
                table: "Settings");

            migrationBuilder.DropColumn(
                name: "Name",
                table: "Settings");

            migrationBuilder.DropColumn(
                name: "StoreId",
                table: "Settings");
        }
    }
}
