name: Docker Build

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - dockerfile: amd64.Dockerfile
                      platform: linux/amd64

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
              with:
                  platforms: all

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./${{ matrix.dockerfile }}
                  platforms: ${{ matrix.platform }}
                  push: true
                  build-args: |
                      GIT_COMMIT=${{ github.sha }}
                      CONFIGURATION_NAME=Altcoins-Release
                  tags: ghcr.io/${{ github.repository_owner }}/btcpayserver:latest
