name: Docker Build

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - dockerfile: amd64.Dockerfile
                      platform: linux/amd64
                      tag: amd64
                    - dockerfile: arm64v8.Dockerfile
                      platform: linux/arm64/v8
                      tag: arm64v8

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
              with:
                  platforms: all

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./${{ matrix.dockerfile }}
                  platforms: ${{ matrix.platform }}
                  push: true
                  build-args: |
                      GIT_COMMIT=${{ github.sha }}
                      CONFIGURATION_NAME=Altcoins-Release
                  tags: ghcr.io/${{ github.repository_owner }}/btcpayserver:latest-${{ matrix.tag }}
            - name: Create and Push Docker Manifests
              env:
                  GHCR_REPO: ghcr.io/${{ github.repository_owner }}/btcpayserver
              run: |
                  # Create and annotate manifest list for the base image
                  docker manifest create $GHCR_REPO:latest $GHCR_REPO:latest-amd64 $GHCR_REPO:latest-arm64v8
                  docker manifest annotate $GHCR_REPO:latest $GHCR_REPO:latest-amd64 --os linux --arch amd64
                  docker manifest annotate $GHCR_REPO:latest $GHCR_REPO:latest-arm64v8 --os linux --arch arm64 --variant v8
                  docker manifest push $GHCR_REPO:latest
